### ISSUE TITLE
Minor updates to the readme file

### ISSUE THREAD

**Issue by simoami** [kenzanlabs/keystone#18]
Temoplate -> Template

LESS, CoffeeScript, TypeScript -> would be nice to see `browserify` in the list (to enable commonjs in browser). Also SASS is now becoming more prominent with the port to libsass and bootstrap, foundation and extjs all adopting SASS as the preferred compiler.

node, karma, protractor -> would love to see `mocha` in the list.

jscs, jslint, html-lint, css lint, less lint -> would love to see `eslint`.

**Comment by obuckley-kenzan** [comment]
Hey Simo, thanks for the feedback.  Replies

1.  Thanks, we will review.
2.  Can you request `browserify` specifically by opening up an issue "request"?  
3.  We have a request open for a compile-sass pipeline here #1 
4.  Mocha is available as part of the node and karma pipelines (if needed, an issue request to update their README's might be in order)
5.  ESLint is supported in our validate-js pipeline - https://github.com/kenzanmedia/pipeline-validate-js

Thanks and let me know if you have any more thoughts!

**Comment by obuckley-kenzan** [comment]
@simoami 
I have created issues to track 
1. see #21 
2. see #22

Everything else seems to be covered.  Please reopen if I missed anything

**Comment by simoami** [comment]
:+1:
