### ISSUE TITLE
Improve usage

### ISSUE THREAD

**Issue by simoami** [kenzanlabs/keystone#19]
improve usage by only calling a single method. the current example requires calling 2 methods; once upon `require('pipeline-example')` and again at `.runTask()`

So instead of:

```
var gulp = require('gulp');
var otherPlugin = require('other-plugin');
var exampleKeystonePipeline = require('pipeline-example')({
  optionA: true,
  optionB: false
});

gulp.task('some-task', function() {
  return gulp.src(['src/**/*.js'])
    .pipe(exampleKeystonePipeline.runTask());
    .pipe(otherPlugin());
    .pipe(gulp.dest('dest/');
});
```

Proposed usage:

```
var pipeline = require('pipeline-example');

gulp.task('some-task', function() {
  return gulp.src(['src/**/*.js'])
    .pipe(pipeline({ optionA: true, optionB: false }));
    // other tasks...
    .pipe(gulp.dest('dest/');
});
```

also no need to specify require('gulp'), so the basic usage doesn't look overwhelming. It's implied gulp is required

**Comment by obuckley-kenzan** [comment]
Hey @simoami , agree.  I actually have an issue open for proposing an alternative, such as like this.  
#7 

I suppose those it depends on if we want each method to take a configuration, instead of at the top level "instantiation".  I like this approach though. 

Thoughts @csharon ?

**Comment by obuckley-kenzan** [comment]
I'm going to make a SASS plugin and try out this new technique.

Unless there are any objections, I would like to close this and keep all conversation related to this enhancement in #7

**Comment by simoami** [comment]
@obuckley-kenzan Thanks for considering. You can go ahead and close.

**Comment by obuckley-kenzan** [comment]
Sounds good, and thanks for the feedback @simoami !
