### ISSUE TITLE
would like a validate HTML pipeline

### ISSUE THREAD

**Issue by obuckley-kenzan** [kenzanlabs/keystone#2]
would like a pipeline for this plugin
https://www.npmjs.com/package/gulp-html-validator

**Comment by thescientist13** [comment]
https://github.com/kenzanlabs/pipeline-validate-html/pull/

**Comment by thescientist13** [comment]
@paul-barry-kenzan 
Hooray, this has been published!  👍 
https://github.com/kenzanlabs/pipeline-validate-html/

Please add this to the active projects section in this repo please!

**Comment by paul-barry-kenzan** [comment]
@thescientist13 
https://github.com/kenzanlabs/keystone/pull/39

**Comment by thescientist13** [comment]
added to active projects!
https://github.com/kenzanlabs/keystone#active-projects
