### ISSUE TITLE
consider making pipelines "static" like

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/keystone#7]
All the plugins seems to have to require being "instantiated" in order to be used, e.g.
```
var minifyPipeline = require('pipeline-minify-js')();
```

It might be better if methods were "static" like by returning an object instead of our current architecture where the return value of the `require` must be called like a function

- https://github.com/kenzanlabs/pipeline-compile-less
- https://github.com/kenzanlabs/pipeline-minify-css
- https://github.com/kenzanlabs/pipeline-minify-js
- https://github.com/kenzanlabs/pipeline-test-node
- https://github.com/kenzanlabs/pipeline-validate-css

cc: @csharon / @jpoo90

**Comment by thescientist13** [comment]
actually, I suppose this is the only way to allow them to be configure them.  Would it be better to expose a setConfig method maybe?

**Comment by obuckley-kenzan** [comment]
Or use a .piperc file
